[package]
name = "akkordcalc"
version = "0.1.0"
authors = ["me <l>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18"

[dependencies.terminal]
version = "0.2"
features = ["crossterm-backend"]